/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ingreso;

import Clases.Notificacion;
import Hacer_habitacion.hacer_habitacion;
import Movimiento.Movimiento_Huespedes;
import Mantenimiento.Ventana_Seleccion_Registrar;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author Clarisse_Naoemi-PC
 */
public class Principal extends javax.swing.JFrame {

    String tema = "javax.swing.plaf.metal.MetalLookAndFeel";

    Notificacion notifi = new Notificacion(this);
    Timer tiempo;

    public void cerrar() {
        String botones[] = {" Cerrar ", " Cancelar"};
        int elegir = JOptionPane.showOptionDialog(this, "¿ Desea Cerrar E Sistema ? ", " AVISO ", 0, 0, null, botones, this);
        if (elegir == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else if (elegir == JOptionPane.CANCEL_OPTION) {
        }
    }

    public Principal() {
        initComponents();

        setLocationRelativeTo(null);
        setResizable(false);

        LookJframe();

        //===========================================================
        ((JPanel) getContentPane()).setOpaque(false);
        ImageIcon f = new ImageIcon(getClass().getResource("/Imagenes/Fondo_Sistema.jpg"));
        JLabel fondo = new JLabel();
        fondo.setIcon(f);
        getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0, 0, f.getIconWidth(), f.getIconHeight());

        //================================================================
        String Formato = "dd - MM -YYYY";
        SimpleDateFormat sdf = new SimpleDateFormat(Formato);

        Date dat = new Date();
        String dia = sdf.format(dat);
        jLabelFecha.setText("Fecha : " + dia);
        //=====================================================

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelCerrar_Sistema = new javax.swing.JLabel();
        jLabelCerrar_Sistema1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelU = new javax.swing.JLabel();
        jLabelUsuarioConectado = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelhORA = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Boton_Mantenimiento = new javax.swing.JButton();
        Boton_HacerHabitacion = new javax.swing.JButton();
        Boton_Movimientos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/INFOR.png"))); // NOI18N

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Mantenimiento");

        jLabelCerrar_Sistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar_Sistema.png"))); // NOI18N
        jLabelCerrar_Sistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrar_SistemaMouseClicked(evt);
            }
        });

        jLabelCerrar_Sistema1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cerrar_Sesion.png"))); // NOI18N
        jLabelCerrar_Sistema1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrar_Sistema1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Reservar Habitacion");

        jLabelU.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelU.setForeground(new java.awt.Color(51, 204, 0));
        jLabelU.setText(">Usuario Conectado :");

        jLabelUsuarioConectado.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelUsuarioConectado.setForeground(new java.awt.Color(51, 204, 0));
        jLabelUsuarioConectado.setText(">");

        jLabelFecha.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelFecha.setForeground(new java.awt.Color(0, 204, 0));
        jLabelFecha.setText(">");

        jLabelhORA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabelhORA.setForeground(new java.awt.Color(0, 204, 0));
        jLabelhORA.setText(">");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Movimiento");

        Boton_Mantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registrar_1.png"))); // NOI18N
        Boton_Mantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_MantenimientoActionPerformed(evt);
            }
        });

        Boton_HacerHabitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Hacer_Habitacion.png"))); // NOI18N
        Boton_HacerHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_HacerHabitacionActionPerformed(evt);
            }
        });

        Boton_Movimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Hacer_Factura.png"))); // NOI18N
        Boton_Movimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_MovimientosActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/information.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabelCerrar_Sistema1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelCerrar_Sistema))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelhORA, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabelU, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelUsuarioConectado, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Boton_Mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Boton_HacerHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addComponent(Boton_Movimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(jLabel5)))))
                .addContainerGap(217, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(369, 369, 369))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelhORA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabelFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Boton_Mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Boton_HacerHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Boton_Movimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel5))
                    .addComponent(jLabel4))
                .addGap(62, 62, 62)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelCerrar_Sistema1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelCerrar_Sistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelU)
                            .addComponent(jLabelUsuarioConectado))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCerrar_SistemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrar_SistemaMouseClicked
        String mensaje = "<html> <body> <b style = \" font-size : 12; color :red; \"> Desea Cerrar El Sistema  </b> </body> </html>";
        int salir = JOptionPane.showConfirmDialog(null, mensaje, "Aviso", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_CANCEL_OPTION);

        if (salir == JOptionPane.YES_OPTION) {
            System.exit(0);
        }

    }//GEN-LAST:event_jLabelCerrar_SistemaMouseClicked

    private void jLabelCerrar_Sistema1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrar_Sistema1MouseClicked
        String mensaje = "<html> <body> <b style = \" font-size : 12; color :red; \"> Desea Cerrar Sesion </b> </body> </html>";
        int opcion = JOptionPane.showConfirmDialog(null, mensaje, "Aviso", JOptionPane.WARNING_MESSAGE);
        if (opcion == JOptionPane.YES_OPTION) {

            Sesion i = new Sesion();
            i.setVisible(true);
            dispose();

        }

    }//GEN-LAST:event_jLabelCerrar_Sistema1MouseClicked

    public class Reloj implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {

            int hora, minuto, segundo;
            GregorianCalendar date = new GregorianCalendar();

            hora = date.get(Calendar.HOUR);
            minuto = date.get(Calendar.MINUTE);
            segundo = date.get(Calendar.SECOND);
            jLabelhORA.setText("Hora : " + hora + " : " + minuto + " : " + segundo);
        }
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        tiempo = new Timer(1000, new Reloj());
        tiempo.start();

    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void Boton_MantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_MantenimientoActionPerformed

        Ventana_Seleccion_Registrar vsr = new Ventana_Seleccion_Registrar();
        vsr.setVisible(true);
        vsr.setLocationRelativeTo(null);


    }//GEN-LAST:event_Boton_MantenimientoActionPerformed

    private void Boton_HacerHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_HacerHabitacionActionPerformed

        hacer_habitacion ah = new hacer_habitacion();
        ah.setVisible(true);

    }//GEN-LAST:event_Boton_HacerHabitacionActionPerformed

    private void Boton_MovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_MovimientosActionPerformed

        Movimiento_Huespedes mh = new Movimiento_Huespedes();
        mh.setVisible(true);
        mh.setLocationRelativeTo(this);

    }//GEN-LAST:event_Boton_MovimientosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        jDialog1.setModal(true);
        jDialog1.setMinimumSize(new Dimension(404, 455));
        jDialog1.setLocationRelativeTo(this);
        jDialog1.setResizable(false);
        jDialog1.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Boton_HacerHabitacion;
    public static javax.swing.JButton Boton_Mantenimiento;
    public static javax.swing.JButton Boton_Movimientos;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCerrar_Sistema;
    private javax.swing.JLabel jLabelCerrar_Sistema1;
    private javax.swing.JLabel jLabelFecha;
    public static javax.swing.JLabel jLabelU;
    public static javax.swing.JLabel jLabelUsuarioConectado;
    private javax.swing.JLabel jLabelhORA;
    // End of variables declaration//GEN-END:variables

    void LookJframe() {

//              try {
//            //UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
//            UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
//            SwingUtilities.updateComponentTreeUI(this);
//        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException e) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
//        }
//          
        try {
            //UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
            UIManager.setLookAndFeel("com.jtattoo.plaf.noire.NoireLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException e) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
        }
    }

    public void LookAndFeel() {

        try {

            UIManager.setLookAndFeel(tema);
            SwingUtilities.updateComponentTreeUI(this);

        } catch (Exception erro) {
            System.out.println("Error al cargar el tema");
        }
    }
}
